global:
  resolve_timeout: 5m

route:
  group_by: ["alertname"]
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 1h
  receiver: "webhook-notifications"

receivers:
  - name: "webhook-notifications"
    webhook_configs:
      - url: "http://localhost:8080/alert" # 本地測試用
        send_resolved: true
